### PR TITLE
SMF 2.1 Converters

### PR DESCRIPTION
**Pull request by jdarwood007**
This is my initial work for getting SMF 2.1 converters working.

- The UI is based on the installer/upgrader
- This uses 4 classes to logically order work, but is in no sense MVC
- "Converter" class is the main class handling all the work for I/O and checks/balances
- "ConverterDb" class is the class that handles all database logic.  This handles getting data to/from the systems as needed.
- "ConverterBase" is the base class all converters will inherit from.  This provides common useful tools/logical information for all converters.  It does make use of late static binding.
- "CleanupDatabase" is a class extending the "ConverterBase" and itself is a step in the conversion process in the sense it rebuilds and corrects issues that occur during the conversion.
- All converters are now named "converter_{FORUM}_to_smf.php" and we have done away with the .sql logic in favor of having something that functions with IDEs.
- I have removed the logic of pointing to a SMF forum and made it assume it can connect to it with a SSI.php connection
- Due to errors/concerns, This will disable database driven sessions and query security checks.

**This is a WIP**
I am looking for feedback and general thoughts.  I've wrote a few converters and did minimal testing.  There is still plenty to test.  Feel free to through forums at the converters to test the conversion.  If we need to test something that can't be resolved, I could use a few forum databases to test against.

### CODE REVIEW

**Comment by Oldiesmann** [comment]
I'll take a look at these more tomorrow and maybe throw some data at them. I have YaBB 2.6 and ElkArte test boards set up on my server already and may put up something else to play with as well.

**Comment by jdarwood007** [comment]
I didn't test against Yabb 2.6 since it was in dev far as I can tell.

**Comment by Oldiesmann** [comment]
As far as I can tell 2.6 is the latest version and 2.7 is in development. Things are pretty messy with the loss of access to the yabbforum domain and server. The person maintaining yabbforumsoftware.com is one of the developers but I don't know how many other team members are there.

**Comment by jdarwood007** [comment]
Ahh, the sourcefordge doesn't have it as a release file, only in the svn trunk

**Pull request merged**
